version: '3.9'
volumes:
  pg_data: {}

services:
  backend:
    image: dimmaryanto93/demo-nke-ops:uploadfile-v1
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        JAR_FILE: demo-nke-ops-1.0.0.jar
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080