version: '3.9'

services:
  wilayah-api:
    image: dimmaryanto93/demo-nke-ops:microservice-wilayah-v1
    build:
      dockerfile: Dockerfile
      context: ./api-wilayah

  nasabah-api:
    image: dimmaryanto93/demo-nke-ops:microservice-nasabah-v1
    build:
      dockerfile: Dockerfile
      context: ./api-nasabah
