apiVersion: v1
kind: Service
metadata:
  name: nasabah-api
spec:
  selector:
    app: nasabah-api
    tier: backend
    version: v1
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: NodePort