spring:
  application:
    name: springweb-jpa

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:example}
    password: ${DATABASE_PASSWORD:example}
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:example}

  jpa:
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    baseline-version: 1
    enabled: ${FLYWAY_ENABLED:true}
    clean-disabled: true

server:
  port: ${SERVER_PORT:8080}