apiVersion: apps/v1
kind: Deployment
metadata:
  name: wilayah-api
  labels:
    app: wilayah-api
    tier: backend
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      name: wilayah-api
      labels:
        app: wilayah-api
        tier: backend
        version: v1
    spec:
      containers:
        - name: wilayah-api
          image: <registry-url>/<username>/demo-nke-ops:microservice-wilayah-v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: webservice
                optional: false
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 200Mi
          livenessProbe:
            httpGet:
              port: http
              path: /actuator/health/liveness
            periodSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              port: http
              path: /actuator/health/readiness
            failureThreshold: 3
            initialDelaySeconds: 3
      restartPolicy: Always
  selector:
    matchLabels:
      app: wilayah-api
      tier: backend
      version: v1
