apiVersion: v1
kind: Service
metadata:
  name: jpa-webservice
spec:
  selector:
    app: jpa-webservice
    tier: backend
    version: v1
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: NodePort